export const initialProducts = [
  {
    id: 1,
    name: 'Notebook Lenovo IdeaPad Slim 3',
    category: 'Notebooks',
    brand: 'Lenovo',
    sku: 'NB-LEN-14-R5',
    cost: 485000,
    price: 629900,
    stock: 3,
    soldMonthly: 11,
    lastSaleDays: 2,
    clicks: 18,
    featured: 'Mas vendido',
    description:
      'Notebook de uso diario con SSD y excelente salida para home office o estudio.',
    specs: {
      Procesador: 'Ryzen 5 7520U',
      RAM: '16GB DDR5',
      Capacidad: 'SSD 512GB',
      Pantalla: '14" FHD',
      Conectividad: 'Wi-Fi 6, BT 5.2, USB-C',
    },
    variants: [
      { label: '8GB / 256GB', stock: 1 },
      { label: '16GB / 512GB', stock: 2 },
    ],
    priceHistory: ['589.900', '612.900', '629.900'],
  },
  {
    id: 2,
    name: 'Mouse Logitech G203 Lightsync',
    category: 'Perifericos',
    brand: 'Logitech',
    sku: 'MOU-LOG-G203',
    cost: 18900,
    price: 25900,
    stock: 12,
    soldMonthly: 23,
    lastSaleDays: 1,
    clicks: 34,
    featured: 'Oferta',
    description:
      'Mouse gamer compacto con sensor preciso y RGB configurable, ideal para entrada al gaming.',
    specs: {
      Sensor: '8000 DPI',
      Botones: '6 programables',
      Conexion: 'USB',
      Iluminacion: 'RGB Lightsync',
      Peso: '85 g',
    },
    variants: [
      { label: 'Negro', stock: 7 },
      { label: 'Blanco', stock: 5 },
    ],
    priceHistory: ['27.900', '26.500', '25.900'],
  },
  {
    id: 3,
    name: 'Memoria Kingston Fury Beast DDR4',
    category: 'Componentes PC',
    brand: 'Kingston',
    sku: 'RAM-KNG-3200',
    cost: 22800,
    price: 31900,
    stock: 6,
    soldMonthly: 16,
    lastSaleDays: 5,
    clicks: 14,
    featured: 'Ultimas unidades',
    description:
      'Memoria lista para upgrade rápido con perfil low-profile y gran compatibilidad.',
    specs: {
      RAM: '16GB',
      Velocidad: '3200MHz',
      Latencia: 'CL16',
      Formato: 'UDIMM',
      Disipador: 'Aluminio negro',
    },
    variants: [
      { label: '8GB', stock: 2 },
      { label: '16GB', stock: 4 },
    ],
    priceHistory: ['29.900', '30.900', '31.900'],
  },
  {
    id: 4,
    name: 'Auriculares Redragon Zeus X',
    category: 'Audio',
    brand: 'Redragon',
    sku: 'AUD-RDG-ZEUSX',
    cost: 41200,
    price: 58900,
    stock: 2,
    soldMonthly: 9,
    lastSaleDays: 8,
    clicks: 21,
    featured: 'Ultimas unidades',
    description:
      'Headset envolvente con micro desmontable y sonido 7.1 para setup gamer.',
    specs: {
      Sonido: '7.1 Virtual',
      Microfono: 'Desmontable',
      Conexion: 'USB + Jack 3.5',
      Compatibilidad: 'PC, PS, Switch',
      Construccion: 'Metal reforzado',
    },
    variants: [
      { label: 'Negro', stock: 1 },
      { label: 'Blanco', stock: 1 },
    ],
    priceHistory: ['54.900', '56.900', '58.900'],
  },
  {
    id: 5,
    name: 'Router TP-Link Archer AX12',
    category: 'Redes',
    brand: 'TP-Link',
    sku: 'NET-TPL-AX12',
    cost: 39900,
    price: 52900,
    stock: 7,
    soldMonthly: 7,
    lastSaleDays: 18,
    clicks: 9,
    featured: 'Nuevo ingreso',
    description:
      'Router Wi-Fi 6 pensado para hogares con streaming, gaming y múltiples dispositivos.',
    specs: {
      WiFi: 'AX1500',
      Bandas: '2.4GHz / 5GHz',
      Puertos: '4x Gigabit',
      Cobertura: 'Hasta 120 m2',
      App: 'Tether',
    },
    variants: [{ label: 'Version global', stock: 7 }],
    priceHistory: ['49.900', '51.900', '52.900'],
  },
  {
    id: 6,
    name: 'Chromecast Google TV HD',
    category: 'Streaming',
    brand: 'Google',
    sku: 'STR-GOO-TVHD',
    cost: 51900,
    price: 69900,
    stock: 5,
    soldMonthly: 13,
    lastSaleDays: 3,
    clicks: 26,
    featured: 'Mas vendido',
    description:
      'Convierte cualquier TV en smart con control remoto, apps y casting instantáneo.',
    specs: {
      Resolucion: '1080p HDR',
      Sistema: 'Google TV',
      Conectividad: 'Wi-Fi, Bluetooth',
      Audio: 'Dolby Digital',
      Extras: 'Control por voz',
    },
    variants: [
      { label: 'Snow', stock: 3 },
      { label: 'Charcoal', stock: 2 },
    ],
    priceHistory: ['65.900', '67.900', '69.900'],
  },
  {
    id: 7,
    name: 'SSD WD Green SN350 NVMe',
    category: 'Componentes PC',
    brand: 'Western Digital',
    sku: 'SSD-WD-500NV',
    cost: 28700,
    price: 38900,
    stock: 14,
    soldMonthly: 19,
    lastSaleDays: 2,
    clicks: 11,
    featured: 'Recomendado',
    description:
      'Upgrade directo para notebooks y PCs con mejor arranque y carga instantánea.',
    specs: {
      Capacidad: '500GB',
      Formato: 'M.2 2280',
      Interfaz: 'PCIe Gen3',
      Lectura: '2400 MB/s',
      Garantia: '3 anos',
    },
    variants: [
      { label: '500GB', stock: 8 },
      { label: '1TB', stock: 6 },
    ],
    priceHistory: ['35.900', '36.900', '38.900'],
  },
  {
    id: 8,
    name: 'Monitor Samsung Odyssey G4',
    category: 'Perifericos',
    brand: 'Samsung',
    sku: 'MON-SAM-G4',
    cost: 221000,
    price: 289900,
    stock: 1,
    soldMonthly: 4,
    lastSaleDays: 49,
    clicks: 7,
    featured: 'Liquidar',
    description:
      'Monitor de 25 pulgadas con 240Hz y panel IPS orientado a esports y respuesta rapida.',
    specs: {
      Panel: 'IPS 25"',
      Frecuencia: '240Hz',
      Tiempo: '1ms',
      Resolucion: 'FHD',
      Conectividad: 'DisplayPort, HDMI',
    },
    variants: [{ label: 'Base original', stock: 1 }],
    priceHistory: ['319.900', '304.900', '289.900'],
  },
]

export const initialCustomers = [
  {
    id: 1,
    name: 'Martina Ruiz',
    phone: '+54 9 11 6421-1402',
    notes: 'Consulta siempre notebooks para diseño.',
    purchases: 4,
  },
  {
    id: 2,
    name: 'Joaquin Lopez',
    phone: '+54 9 11 5188-2901',
    notes: 'Compra periféricos cada 45 dias.',
    purchases: 7,
  },
  {
    id: 3,
    name: 'Valentina Sosa',
    phone: '+54 9 11 3877-0092',
    notes: 'Prefiere pagar por transferencia.',
    purchases: 3,
  },
]

export const categories = [
  'Todos',
  'Notebooks',
  'Componentes PC',
  'Perifericos',
  'Audio',
  'Redes',
  'Streaming',
]

export const brands = [
  'Todas',
  'Lenovo',
  'Logitech',
  'Kingston',
  'Redragon',
  'TP-Link',
  'Google',
  'Western Digital',
  'Samsung',
]

export const paymentMethods = ['Efectivo', 'Transferencia', 'Mercado Pago']
